name: GitHub Classroom Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Build with Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.6.3
      - name: Build app
        run: mvn -f pom.xml --batch-mode --batch-mode --update-snapshots clean install -DskipTests
      - name: Build Image
        run: docker compose build
      - name: Run Container
        run: docker compose up -d
      - name: Sleep for 40 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '50s'
      - name: Run JUnit Tests
        run: docker compose run --rm app mvn test
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'
      - name: Stop Containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
